/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData th_large = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_1_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xf0ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xf14e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
